"""Digit-level authenticity checks.

Both digit tests are run per column, never on all columns pooled together:
pooling variables that carry different units produces a digit distribution
with no expected shape, so any deviation from it is meaningless.

Benford's law in particular is easy to misapply. It describes data produced by
multiplicative processes and spanning many orders of magnitude -- financial
totals, population counts. Ordinary bounded measurements do not follow it even
when they are entirely honest: a Gamma-distributed clinical variable covering
two orders of magnitude fails the test routinely. So the check demands a wide
spread before it will run at all, and never raises more than a moderate flag.
"""

from __future__ import annotations

import functools
import math
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

from scifraudscan.models import Finding, clear, flag, not_applicable
from scifraudscan.utils import (
    cramers_v,
    is_index_like,
    numeric_frame,
    order_of_magnitude_span,
    terminal_digits,
)

# Nigrini (2012) mean absolute deviation cut-offs for the first digit.
MAD_MARGINAL = 0.012
MAD_NONCONFORM = 0.015
BENFORD_MIN_N = 150
BENFORD_MIN_SPAN = 3.0
DIGIT_MIN_N = 100
ALPHA = 0.01
# Flag a column only when its digit non-uniformity exceeds this quantile of
# real published data. Calibrated on 150 datasets and checked on 150 held out,
# where it fires on 1.5% of testable columns.
DIGIT_REFERENCE_QUANTILE = 0.975
DIGIT_REFERENCE_FILE = (
    Path(__file__).resolve().parent.parent / "reference" / "digit_preference_reference.csv"
)


@functools.lru_cache(maxsize=1)
def _digit_reference() -> tuple[np.ndarray, np.ndarray]:
    """Cramer's V for terminal digits across columns of real datasets.

    Terminal digits are not uniform in real data even when nothing is wrong,
    so a theoretical null flags ordinary columns: at the old threshold of
    V >= 0.10, 40% of real full-precision columns were flagged. This is the
    same lesson as the baseline p-value reference.
    """
    table = pd.read_csv(DIGIT_REFERENCE_FILE)
    return (
        table["cramers_v"].to_numpy(dtype=float),
        table["quantile"].to_numpy(dtype=float),
    )


def digit_preference_percentile(v: float) -> float:
    """Share of real columns with digit non-uniformity at or below `v`."""
    values, quantiles = _digit_reference()
    return float(np.interp(v, values, quantiles, left=0.0, right=1.0))


BENFORD_EXPECTED = np.array([math.log10(1 + 1 / digit) for digit in range(1, 10)])


def benford_law(df: pd.DataFrame, scale_invariant: bool = False) -> Finding:
    """Benford's first-digit law. Off unless the caller asserts it applies.

    Benford describes quantities produced by multiplicative processes across
    many orders of magnitude. Whether a variable is one of those is a fact
    about the world, not about the column, so it cannot be inferred here. Left
    to decide for itself the check fired on 74% of the real datasets where it
    was eligible. It now runs only when the caller states the variable is
    scale-invariant.
    """
    check = "Benford First Digit"
    if not scale_invariant:
        return not_applicable(
            check,
            "Not run. Benford's law applies to quantities generated by multiplicative "
            "processes spanning many orders of magnitude; whether this variable is one "
            "cannot be determined from the data. Pass scale_invariant=True to assert it.",
        )
    eligible: list[tuple[str, np.ndarray]] = []
    skipped: list[dict[str, object]] = []
    for column, raw in _columns(df):
        values = raw[raw != 0]
        span = order_of_magnitude_span(values)
        if len(values) < BENFORD_MIN_N or span < BENFORD_MIN_SPAN:
            skipped.append(
                {"column": column, "n": len(values), "order_of_magnitude_span": round(span, 3)}
            )
            continue
        eligible.append((column, values))

    if not eligible:
        return not_applicable(
            check,
            f"No column has both n >= {BENFORD_MIN_N} and a spread of >= {BENFORD_MIN_SPAN} "
            "orders of magnitude, which Benford's law requires.",
            skipped_columns=skipped[:20],
        )

    results = [_benford_column(column, values) for column, values in eligible]
    flagged = [r for r in results if r["mad"] > MAD_NONCONFORM and r["p_value"] < ALPHA]
    if not flagged:
        return clear(
            check,
            f"{len(results)} eligible columns conform to Benford's law "
            f"(MAD <= {MAD_NONCONFORM} or chi-square p >= {ALPHA}).",
            columns=results,
        )
    worst = max(flagged, key=lambda r: r["mad"])
    # Capped at moderate on purpose: non-conformity is common in honest
    # measurement data, so this is never strong evidence on its own.
    return flag(
        check,
        "moderate",
        f"{len(flagged)} of {len(results)} eligible columns deviate from Benford's law; "
        f"worst is '{worst['column']}' with MAD={worst['mad']:.4f} (p={worst['p_value']:.3g}). "
        "Benford non-conformity is weak evidence unless the variable is known to be "
        "scale-invariant.",
        flagged_columns=flagged,
        evaluated_columns=results,
        mad_thresholds={"marginal": MAD_MARGINAL, "nonconformity": MAD_NONCONFORM},
    )


def digit_preference(df: pd.DataFrame) -> Finding:
    check = "Terminal Digit Preference"
    results: list[dict[str, object]] = []
    skipped: list[dict[str, object]] = []
    coarse: list[dict[str, object]] = []
    for column, values in _columns(df):
        digits = terminal_digits(values)
        if len(digits) < DIGIT_MIN_N:
            skipped.append({"column": column, "n": len(digits)})
            continue
        # A column that never shows some terminal digits is recorded more
        # coarsely than its last place. Granularity and human heaping cannot be
        # told apart from the values alone -- "every value ends in 0 or 5" fits
        # a scale marked in fives just as well as rounding by hand -- so this
        # is not applicable rather than positive. In the reference data every
        # such column exceeded the old threshold: all of them would have been
        # flagged, and none of them had been shown to be anything.
        if (np.bincount(digits, minlength=10) == 0).any():
            coarse.append({"column": column, "n": len(digits)})
            continue
        results.append(_digit_column(column, digits))

    if not results:
        reason = (
            f"{len(coarse)} columns are recorded too coarsely for their terminal digits "
            "to carry information, and no other column qualifies."
            if coarse
            else f"No column has {DIGIT_MIN_N} or more usable terminal digits."
        )
        return not_applicable(
            check, reason, skipped_columns=skipped[:20], coarse_columns=coarse[:20]
        )

    values_grid, quantiles = _digit_reference()
    threshold = float(np.interp(DIGIT_REFERENCE_QUANTILE, quantiles, values_grid))
    flagged = [r for r in results if r["p_value"] < ALPHA and r["cramers_v"] >= threshold]
    coarse_note = (
        f" {len(coarse)} further columns are too coarsely recorded to test." if coarse else ""
    )
    shared: dict[str, object] = {
        "evaluated_columns": results,
        "coarse_columns": coarse[:20],
        "threshold_cramers_v": round(threshold, 4),
        "threshold_is": (
            f"{DIGIT_REFERENCE_QUANTILE:.1%} quantile of real published columns"
        ),
    }
    for result in results:
        result["percentile_among_real_columns"] = round(
            digit_preference_percentile(float(result["cramers_v"])), 4
        )
    if not flagged:
        highest = max(results, key=lambda r: r["cramers_v"])
        return clear(
            check,
            f"Terminal digits in {len(results)} columns are no more uneven than in "
            f"ordinary published data; the most uneven, '{highest['column']}', sits above "
            f"{float(highest['percentile_among_real_columns']):.0%} of real columns "
            f"(flagging starts at V={threshold:.2f}).{coarse_note}",
            **shared,
        )
    worst = max(flagged, key=lambda r: r["cramers_v"])
    v = float(worst["cramers_v"])
    percentile = digit_preference_percentile(v)
    return flag(
        check,
        "high" if percentile >= 0.995 else "moderate",
        f"{len(flagged)} of {len(results)} columns have more uneven terminal digits than "
        f"{DIGIT_REFERENCE_QUANTILE:.0%} of real published columns; worst is "
        f"'{worst['column']}' (digit {worst['top_digit']} at {float(worst['top_rate']):.1%}, "
        f"Cramer's V={v:.3f}, above {percentile:.1%} of real columns).{coarse_note}",
        flagged_columns=flagged,
        worst_percentile=round(percentile, 4),
        **shared,
    )


def repeated_increments(df: pd.DataFrame, min_n: int = 20) -> Finding:
    """Columns whose consecutive differences repeat far more than real data would."""
    check = "Repeated Increments"
    results: list[dict[str, object]] = []
    for column, values in _columns(df):
        if len(values) < min_n:
            continue
        # Integer-valued measures repeat their increments for ordinary reasons.
        if np.allclose(values, np.rint(values)):
            continue
        diffs = np.round(np.diff(values), 10)
        if len(diffs) < min_n - 1 or np.allclose(values, values[0]):
            continue
        unique_rate = len(set(diffs.tolist())) / len(diffs)
        if unique_rate < 0.25:
            results.append(
                {
                    "column": column,
                    "n": len(values),
                    "distinct_increment_rate": round(float(unique_rate), 6),
                    "most_common_increment": float(pd.Series(diffs).mode().iloc[0]),
                }
            )

    if not results:
        return clear(check, "No column is built from a small set of repeated increments.")
    worst = min(results, key=lambda r: r["distinct_increment_rate"])
    rate = float(worst["distinct_increment_rate"])
    severity = "high" if rate < 0.05 else "moderate" if rate < 0.15 else "low"
    return flag(
        check,
        severity,
        f"{len(results)} columns advance by a small set of repeated steps; "
        f"'{worst['column']}' has only {rate:.1%} distinct increments.",
        columns=results,
    )


def run_authenticity_checks(
    df: pd.DataFrame, benford_scale_invariant: bool = False
) -> list[Finding]:
    return [
        benford_law(df, benford_scale_invariant),
        digit_preference(df),
        repeated_increments(df),
    ]


def _columns(df: pd.DataFrame):
    """Measurement columns only: row counters and ID sequences are skipped."""
    num = numeric_frame(df)
    for column in num.columns:
        values = num[column].dropna().to_numpy(dtype=float)
        if is_index_like(values):
            continue
        yield str(column), values


def index_like_columns(df: pd.DataFrame) -> list[str]:
    num = numeric_frame(df)
    return [
        str(column)
        for column in num.columns
        if is_index_like(num[column].dropna().to_numpy(dtype=float))
    ]


def _benford_column(column: str, values: np.ndarray) -> dict[str, object]:
    observed = _first_digit_counts(values)
    total = float(observed.sum())
    expected = BENFORD_EXPECTED * total
    chi_square = float(np.sum((observed - expected) ** 2 / expected))
    p_value = float(stats.chi2.sf(chi_square, df=8))
    mad = float(np.mean(np.abs(observed / total - BENFORD_EXPECTED)))
    return {
        "column": column,
        "n": int(total),
        "observed_counts": observed.astype(int).tolist(),
        "expected_probabilities": [round(float(p), 6) for p in BENFORD_EXPECTED],
        "chi_square": round(chi_square, 6),
        "p_value": float(f"{p_value:.6g}"),
        "mad": round(mad, 6),
        "order_of_magnitude_span": round(order_of_magnitude_span(values), 3),
    }


def _digit_column(column: str, digits: np.ndarray) -> dict[str, object]:
    counts = np.bincount(digits, minlength=10).astype(float)
    total = counts.sum()
    chi_square = float(stats.chisquare(counts, np.full(10, total / 10)).statistic)
    p_value = float(stats.chi2.sf(chi_square, df=9))
    return {
        "column": column,
        "n": int(total),
        "counts_0_to_9": counts.astype(int).tolist(),
        "top_digit": int(np.argmax(counts)),
        "top_rate": round(float(counts.max() / total), 6),
        "entropy_bits": round(float(stats.entropy(counts / total, base=2)), 6),
        "chi_square": round(chi_square, 6),
        "p_value": float(f"{p_value:.6g}"),
        "cramers_v": round(cramers_v(counts, chi_square), 6),
    }


def _first_digit_counts(values: np.ndarray) -> np.ndarray:
    counts = np.zeros(9, dtype=float)
    for value in np.abs(values):
        text = f"{value:.12e}"
        digit = int(text[0])
        if 1 <= digit <= 9:
            counts[digit - 1] += 1
    return counts

